# Archivo: .streamlit/secrets.toml
# Agregar estos secrets en Streamlit Cloud

SUPABASE_KEY = "tu_anon_key_de_supabase"
PASSWORD_ADMIN = "OTE.Admin2026"
EMPRESA_ID = "9b38d84f-3e3a-4951-9535-9df638ef0829"
RESEND_KEY = "tu_resend_api_key"
